'use strict';
const canvas=document.getElementById('game'),g=canvas.getContext('2d'),$=id=>document.getElementById(id);
let state='menu',t=0,remaining=60,score=0,hp=3,inv=0,intro=0,muted=true,audio,last=0,best=0;
try{best=Number(localStorage.getItem('kibelBest')||0)}catch{}
const keys=new Set(),player={x:360,y:515,r:13},walls=[{x:30,y:110,w:190,h:20},{x:250,y:110,w:190,h:20},{x:470,y:110,w:190,h:20},{x:210,y:30,w:10,h:80},{x:430,y:30,w:10,h:80}];
let rolls=[],enemies=[],particles=[];
function beep(f=400){if(muted)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),v=audio.createGain();o.type='square';o.frequency.value=f;v.gain.setValueAtTime(.035,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.connect(v);v.connect(audio.destination);o.start();o.stop(audio.currentTime+.13)}catch{}}
function say(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(say.timer);say.timer=setTimeout(()=>$('toast').style.display='none',2200)}
function hud(){$('score').textContent=score+' / 8';$('time').textContent=Math.ceil(remaining);$('hp').textContent='● '.repeat(hp)+'○ '.repeat(3-hp)}
function begin(){keys.clear();score=0;hp=3;remaining=60;inv=0;intro=0;player.x=360;player.y=515;rolls=[[80,170],[630,165],[350,175],[75,325],[630,330],[180,465],[545,485],[350,335]].map(([x,y])=>({x,y}));enemies=[{x:200,y:235,vx:110,vy:60},{x:520,y:400,vx:-130,vy:70},{x:340,y:280,vx:80,vy:-110}];particles=[];state='intro';$('overlay').style.display='none';$('pause').textContent='PAUZA';hud();say('03:47 · Zwykła noc w niezwykłym kiblu.');beep(160)}
function end(win){state='end';keys.clear();let result=Math.ceil(remaining*10)+hp*100;if(win&&result>best){best=result;try{localStorage.setItem('kibelBest',best)}catch{}}$('tag').textContent=win?'MISJA: WYJŚCIE Z KIBLA — WYKONANA':'TO BYŁA DŁUGA NOC';$('heading').innerHTML=win?'ŚWIEŻE POWIETRZE.<br>WRESZCIE.':'KIBEL CIĘ<br>POKONAŁ.';$('copy').textContent=win?`Uciekłeś z zapasem papieru. Wynik: ${result}. Rekord: ${best}. Następnym razem wybierz inny klub.`:(hp<=0?'Przepychacze odebrały Ci resztki spokoju. ':'Czas minął. Klub zamknięty, a Ty dalej w toalecie. ')+`Zebrane rolki: ${score}/8.`;$('start').textContent='JESZCZE JEDNA NOC →';$('overlay').style.display='flex';beep(win?750:90)}
function pause(){if(state==='play'){state='paused';keys.clear();$('pause').textContent='WZNÓW';say('PAUZA · złap oddech')}else if(state==='paused'){state='play';$('pause').textContent='PAUZA';$('toast').style.display='none'}}
function person(x,y,color,bend=false){g.fillStyle='#07151188';g.beginPath();g.ellipse(x,y+16,19,8,0,0,7);g.fill();g.fillStyle=color;g.fillRect(x-12,y-6,24,25);g.fillStyle='#edb88d';g.beginPath();g.arc(x+(bend?8:0),y-13,10,0,7);g.fill();g.fillStyle='#171b20';g.fillRect(x-9,y+17,7,8);g.fillRect(x+3,y+17,7,8)}
function draw(){g.fillStyle='#18332f';g.fillRect(0,0,720,600);g.strokeStyle='#2b4941';g.lineWidth=1;for(let x=0;x<720;x+=40){g.beginPath();g.moveTo(x,0);g.lineTo(x,600);g.stroke()}for(let y=0;y<600;y+=40){g.beginPath();g.moveTo(0,y);g.lineTo(720,y);g.stroke()}g.fillStyle='#314940';g.fillRect(0,0,720,18);g.fillRect(0,0,18,600);g.fillRect(702,0,18,600);g.fillRect(0,582,720,18);
for(let x of [118,340,560]){g.fillStyle='#aac7ac';g.fillRect(x-25,32,50,18);g.beginPath();g.ellipse(x,74,26,31,0,0,7);g.fill();g.fillStyle='#315347';g.beginPath();g.ellipse(x,75,16,20,0,0,7);g.fill()}
for(let w of walls){g.fillStyle='#708576';g.fillRect(w.x,w.y,w.w,w.h);g.fillStyle='#afbea0';g.fillRect(w.x,w.y,w.w,3)}
g.fillStyle=score===8?'#ceff57':'#53695c';g.fillRect(308,565,104,32);g.fillStyle='#101b12';g.font='bold 13px monospace';g.textAlign='center';g.fillText(score===8?'WYJŚCIE ↓':'ZAMKNIĘTE',360,587);
g.fillStyle='#668275';g.fillRect(250,210,220,45);g.fillStyle='#a7c3b1';g.fillRect(265,217,65,28);g.fillRect(388,217,65,28);g.fillStyle='#203e39';g.fillRect(272,222,51,16);g.fillRect(395,222,51,16);
g.save();g.translate(88,420);g.rotate(-.18);g.fillStyle='#af76ba';g.font='italic bold 18px monospace';g.fillText('TU BYŁ SENS',0,0);g.restore();
if(state==='intro'||state==='menu'){let bend=state==='intro'&&intro<1.7;person(310,270,'#a871c1',bend);person(400,275,'#cf784d',bend);if(state==='menu'||intro<1.5){g.fillStyle='#eee9d9';g.fillRect(342,244,30,3);g.fillRect(350,235,25,3)}g.fillStyle='#e3eddc';g.font='12px monospace';g.fillText(state==='intro'&&intro>1.7?'Ej… czemu przepychacz się rusza?':'„Tylko na chwilę…”',360,320);return}
for(let r of rolls){g.fillStyle='#ceff5722';g.beginPath();g.arc(r.x,r.y,24+Math.sin(t*3)*3,0,7);g.fill();g.fillStyle='#f1f1d8';g.fillRect(r.x-9,r.y-10,18,23);g.fillStyle='#ccd8b9';g.beginPath();g.ellipse(r.x,r.y-10,9,5,0,0,7);g.fill();g.fillStyle='#526248';g.beginPath();g.ellipse(r.x,r.y-10,3,2,0,0,7);g.fill()}
for(let e of enemies){g.save();g.translate(e.x,e.y);g.rotate(Math.sin(t*4+e.x)*.4);g.fillStyle='#c89e6b';g.fillRect(-3,-20,6,31);g.fillStyle='#ed776a';g.beginPath();g.arc(0,15,15,Math.PI,0);g.fill();g.fillRect(-17,14,34,5);g.restore()}
if(inv<=0||Math.floor(t*12)%2)person(player.x,player.y,'#ceff57');for(let p of particles){g.globalAlpha=p.life;g.fillStyle='#ceff57';g.fillRect(p.x,p.y,4,4)}g.globalAlpha=1;if(state==='paused'){g.fillStyle='#08120ab8';g.fillRect(0,0,720,600);g.fillStyle='#ceff57';g.font='bold 36px monospace';g.fillText('PAUZA',360,300)}}
function blocked(x,y){return x<33||x>687||y<150||y>558|| (x>235&&x<485&&y>192&&y<270)}
function update(dt){t+=dt;if(state==='intro'){intro+=dt;if(intro>3.3){state='play';say('Zbierz papier. Nie zadawaj pytań.')}return}if(state!=='play')return;remaining-=dt;inv-=dt;if(remaining<=0){remaining=0;hud();end(false);return}let dx=Number(keys.has('right'))-Number(keys.has('left')),dy=Number(keys.has('down'))-Number(keys.has('up')),norm=Math.hypot(dx,dy)||1;let nx=player.x+dx/norm*210*dt,ny=player.y+dy/norm*210*dt;if(!blocked(nx,player.y))player.x=nx;if(!blocked(player.x,ny))player.y=ny;
for(let i=rolls.length-1;i>=0;i--){let r=rolls[i];if(Math.hypot(player.x-r.x,player.y-r.y)<28){rolls.splice(i,1);score++;beep(350+score*55);for(let n=0;n<12;n++)particles.push({x:r.x,y:r.y,vx:(Math.random()-.5)*150,vy:(Math.random()-.5)*150,life:1});if(score===8)say('DRZWI OTWARTE! Zielone wyjście na dole.')}}
for(let e of enemies){e.x+=e.vx*dt;e.y+=e.vy*dt;if(e.x<45||e.x>675){e.vx*=-1;e.x=Math.max(45,Math.min(675,e.x))}if(e.y<165||e.y>530){e.vy*=-1;e.y=Math.max(165,Math.min(530,e.y))}if(inv<=0&&Math.hypot(e.x-player.x,e.y-player.y)<29){hp--;inv=1.8;beep(100);say('AUĆ. Toaleta stawia opór.');if(hp<=0){hud();end(false);return}}}for(let p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt*2}particles=particles.filter(p=>p.life>0);hud();if(score===8&&player.y>540&&player.x>305&&player.x<415)end(true)}
const mapping={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};
window.addEventListener('keydown',e=>{let dir=mapping[e.key]||mapping[e.key.toLowerCase()];if(dir){e.preventDefault();keys.add(dir)}if(e.key==='Escape'&&!e.repeat)pause()});window.addEventListener('keyup',e=>keys.delete(mapping[e.key]||mapping[e.key.toLowerCase()]));window.addEventListener('blur',()=>{keys.clear();if(state==='play')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='play')pause()});
for(let b of document.querySelectorAll('[data-dir]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.dir)});for(let ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.dir))}
$('start').onclick=begin;$('pause').onclick=pause;$('sound').onclick=()=>{muted=!muted;$('sound').textContent='DŹWIĘK: '+(muted?'OFF':'ON');beep()};
function frame(ms){let dt=Math.min((ms-last)/1000,.04);last=ms;update(dt);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
